// Counting DNA Nucleotides

// http://rosalind.info/problems/dna/

#include <iostream>

using namespace std;

int main()
{
    string s="CTAACGTATAAAGATCGATATTTTCCAGGAATAACTTCACGGGATGACGTTGCGCGATCATAGATCCTGCTGAATTAATGTCGTGTCCCGCCTGCCACCAAGGGGAACGGAAAACAGTCTTGTTGGTCTGTCGCATGGACCTAGCACATTCTCATTATATAAGCAACAAAAACGTCCGGGAATGATCGTGCACGTCTAGGGTGTCAATCACAAATGAATTGTCGCGGGTATCGCGCACCGATTCACACAAAGGCTTCTACATCGCCATGCCAGACGTTTCCCTAGAGACCGGCACACGTGGTCATGTTACAGCCGTCAGATCCGATACCCGCTTCCGGTACGATTACTACTAATCGTCTGGCGTTATTTGACGTGGTTTCCAGTGACGCAGTTGATAACTGAGTGACTTAGTAACCTGTGGGAATACAAGGGTCGCATTACAACGTGAGGCACACTCGGTGCAGGACCTAACCACGCGAAAACACTAATATTGCTCCTATGAAGATATGGTATTTAACTCAGTCGCAGTCCCGGGCACTAGACCTCGATGATGGTTGAATCATCGAACGTAGAATAAACCACGTCTGTAAATCTGTCGGGAAATCTTACGGAATTCCTTATTGGACGGGAGTATTGATCAGTCTACTCTTCGAATTCTCGAACTCACCGTGCCGATGCTAAAAGCTTAACTCTATACACAGTCCATGATTCCTTCTAGTGAATACTGATAGAATATAGCAGTCAGCTATTGGGTAAGTGTGACAAACCCCAAGGTTATACCAATTGCAAAACAACACGGGTATGAATAGCAGTGGGGGCCGCTCACATCCTTATTCAAGCAAGGTCGATTAAAATCGATAAGCGCTTTTCACGAACGGTCTGTAGTGTGACGTAAAACTAGAGTG";

    for(int i=0; i<s.size(); i++){
        if(s[i]=='T'){
            s[i]='U';
        }
        if(s[i]=='C'){
            c++;
        }
        if(s[i]=='G'){
            g++;
        }
        if(s[i]=='T'){
            t++;
        }
    }
    
    cout << a << " "<< c << " "<< g << " "<< t;
    return 0;
}
