//Computing GC Content

// http://rosalind.info/problems/gc/

//run one by one all strings

#include <iostream>

using namespace std;

int main()
{
    string s="CTAACGTATAAAGATCGATATTTTCCAGGAATAACTTCACGGGATGACGTTGCGCGATCATAGATCCTGCTGAATTAATGTCGTGTCCCGCCTGCCACCAAGGGGAACGGAAAACAGTCTTGTTGGTCTGTCGCATGGACCTAGCACATTCTCATTATATAAGCAACAAAAACGTCCGGGAATGATCGTGCACGTCTAGGGTGTCAATCACAAATGAATTGTCGCGGGTATCGCGCACCGATTCACACAAAGGCTTCTACATCGCCATGCCAGACGTTTCCCTAGAGACCGGCACACGTGGTCATGTTACAGCCGTCAGATCCGATACCCGCTTCCGGTACGATTACTACTAATCGTCTGGCGTTATTTGACGTGGTTTCCAGTGACGCAGTTGATAACTGAGTGACTTAGTAACCTGTGGGAATACAAGGGTCGCATTACAACGTGAGGCACACTCGGTGCAGGACCTAACCACGCGAAAACACTAATATTGCTCCTATGAAGATATGGTATTTAACTCAGTCGCAGTCCCGGGCACTAGACCTCGATGATGGTTGAATCATCGAACGTAGAATAAACCACGTCTGTAAATCTGTCGGGAAATCTTACGGAATTCCTTATTGGACGGGAGTATTGATCAGTCTACTCTTCGAATTCTCGAACTCACCGTGCCGATGCTAAAAGCTTAACTCTATACACAGTCCATGATTCCTTCTAGTGAATACTGATAGAATATAGCAGTCAGCTATTGGGTAAGTGTGACAAACCCCAAGGTTATACCAATTGCAAAACAACACGGGTATGAATAGCAGTGGGGGCCGCTCACATCCTTATTCAAGCAAGGTCGATTAAAATCGATAAGCGCTTTTCACGAACGGTCTGTAGTGTGACGTAAAACTAGAGTG";
    double gc(8.0);
    
    for(int i=0; i<s.size(); i++){
        if(s[i]=='G' || s[i]=='C'){
            gc++;
        }
    }
    gc= double(gc*100);
    float con= gc/s.size();
    cout << con;
    return 0;
}
