// Transcribing DNA into RNA

// http://rosalind.info/problems/rna/

#include <iostream>

using namespace std;

int main()
{
    string s="TAGAAAATCCGTACCGGAATGTGGACCCTGCTTCCTACTCGTGATGCCATTGGCATCGATGCGCTCACTAGATAGCATTTTTCGTAAGCGTTGAGTTATGGGGATGCTCTAGAGTTACCTCAGTTGGGGGGGACAACGGAGTAATTCTCAGCCCTCCAATCCTCAGGGCGCCGATGGCATATAAGCAGTTAGTATCGGGATACGGCCCGGCATCTTGTAGTTTATATTACCTGCTAGATACTCGCTTGCAGTCATGTCCACAGCGCGTCACCCGCCCAGAATTTTGTATAGATTCCTTCAGTGCCATCTTCGATGTGGCCACGCCAAGAACTCTGTGACCTCGTGGTTACTTCGTGGCTGATTTCAGCGATGCGAAGTAGGAGCCCGTCATAGCTTAAACTCCGTACTCTCGCCAACGAACCCCCTAAAATGTGCTCACGACTGGTCAAACTGCATATGGTCCGAATACTCACAGTGATTAATTAGCTGGTACTGCTCTGCGGATCTCTGTACGGTCTAAACAAGACGCGGAATTGAAGGAGAACACACATGACCACTATGAAACCGACCAAGGATCCTACAGCCCATTGGTCCAACGTTTCTTTTTGGCCAGGGATGGGTTTAGGAGCATGCTTTACTAATCAGTCCGAAGGCCACGTGGCGCCGATGGTGGGATATAACGGCGTGCGTGGACATGAAGCGCCAGATAGCATCGGTGTGTTATGCAGCGTGACGCTTGTTGTGAGGCGACATTAGCGTTTAACGTCTGGTCGGGTGTTGGTCTGTCTTGCGTACTACCATGATAAAGGTTTGTGGTCCTGCTCGAGCGGACTATTCCTACCGGGCTCAAGGGCTCAATGCAATACACCAAGTCTAACAAATATCTTTTTCGTGGCCCTAATGCTCACCGGTCGTTGCGCTCCCCCATCTTAGACAAATATGACTGGTGGTT";

    for(int i=0; i<s.size(); i++){
        if(s[i]=='T'){
            s[i]='U';
        }
    }
    
    cout <<s;
    return 0;
}
