// Finding a Motif in DNA

// http://rosalind.info/problems/subs/

#include <iostream>
#include <vector>

using namespace std;

int main()
{
   string s="CTAACTTATAACTTATAATTACTTATAGAATCCGGTCAATACACTTATACTGAGCGGGTACTTATAAATCACTTATATGTAACTTATAGCTACTTATAGCAGACTTATAAACTTATAGACCCGAAGTGAAAGTTACGAGTATAGTACCCACTTATAGGCCAACTTATAGGTCTACTTATATCACATGCTTCGATCCACTTATAACTTATAACTTATAAGACTTATACACTTATAGACTTATAAGAAGGCACTTATAACTTATACGGAACTTATAACACTTATAACTTATACGAACTTATAAGTGGTCCACTTATATACTTATAACTTATAAACTTATATAAAAACTCTACTTATAGTTACTTATACACTTATACTACTTATAGATAACTTATAACTTATAACTTATAGACTTATATACTTATAACTTATAGAAGGTAACTTATAATACTTATAGACCACTTATAGTGTCACTTATATCAGCACTTATAACTTATAGACTTATAACTTATATACTTATATTTGCGACACTTATATGTACTTATATTAACTTATAATTACTTATAAACCTACTTATAGTCTAGACTTATAACTTATAACTTATAATGACTGTCGACTTATATACTTATACTCTGGACCGTACTTATAACTTATACGGACTTATAACTTATAAACTCGAACTTATAACACTTATAACTTATAACTTATAAGACTTATATGCACACTTATACATACTTATAACTTATACACTTATAAAACTTATAGGAAGACTTATACGGCACTTATAGCGTGACTTATAACTTATAAGTCACTTATAGGTGACTTATAACTTATAGGGGGGACTTATAACTTATA";
   string t="ACTTATAAC";
   
   vector<int> res;
   
   for(int i=0; i<s.size()-t.size(); i++){
       if(s.substr(i, t.size())==t){
           res.push_back(i+1);
       }
   }
   for(int i=0; i<res.size(); i++){
       cout << res[i]<< " ";
   }
   
   return 0;
}
